### PR TITLE
2.0.1 electron 0.30.6

### PR DESCRIPTION
**Pull request by mash**
I needed node-serialport to be above v2.0.0 to make serialport-electron to work on Mac OSX 10.11/El Capitan

see https://github.com/voodootikigod/node-serialport/commit/c2e00928759b77e38411f58913402afd3424dac4

### CODE REVIEW

**Comment by mash** [comment]
The commits seems large but what I did was merge voodootikigod/master into ddm/master and fixed conflicts in `package.json` and `README.markdown`

**Comment by ddm** [comment]
I'm really sorry I never noticed this pull request. I just merged it, hopefully it is still useful to someone.

**Comment by ddm** [comment]
@mash Sincere apologies for being more than late on this one.

For anyone looking at this, I believe this fork is no longer needed. My understanding is that recent versions of node/electron/serialport might work as expected using the upstream versions. Ping me if this is not the case...

**Comment by mash** [comment]
@ddm ok, no problem, I'll try upstream serialport when I need to next time.

**Pull request merged**
